sudo: required
language: generic
services:
  - docker
env:
  global:
    - git config --global user.email "jcayouette@suse.com"
    - git config --global user.name "jcayouette"
    - secure: n3µ:üS܊DBëùùɖ°öÁޫD8Ø(iñ)®§óί@»â-èɾ
before_install:
- echo $super_secret_password | gpg --passphrase-fd 0 super_secret.txt.gpg
- git clone https://github.com/uyuni-project/uyuni-docs
- cd uyuni-docs/
- git checkout gh-pages
- rm -rf uyuni/3.2/*
- git clone https://github.com/uyuni-project/uyuni-docs-publisher
- cd uyuni-docs-publisher
- docker pull antora/antora
- docker images
- docker run -u $UID -v `pwd`:/antora --rm -t antora/antora --cache-dir=./.cache/antora uyuni-publisher.yml
- cp -r public/uyuni/3.2/* ../uyuni/
- cd ../
- git remote rm origin
- git remote add origin https://jcayouette:$super_secret_password@github.com/uyuni-project/uyuni-docs.git
- git add .
- git commit -am "New travis commit to 3.2"
- git push --set-upstream origin gh-pages
- pwd
