sudo: required
language: generic
services:
  - docker
env:
  global:
    - GITHUB_REPO: uyuni-project/uyuni-docs
    - secure: "Ua/qo1Ou32rv+Oa0Xop+FKu4OpPT6fBRaARjTBuMHKrdWW9jy/8sKc9GIH/bwakWjxSYlp2I/JdUURaXUBPkxcevHEgrkNT1FQzfoHZfsaBQO6zTGzIzO2lQ0NVpPvrK0Ky/LFhRTuJ/MiTjudFXvi9M+ZRYLdbq2TOMyD6gwhd73aJX/GitASr/GsRWkaX9xAjXeTfeFc4GJdGwhkkLZL8PrWbc077Pzp+kkGAtqpZx0/jJu3+At38z5X+CvU9gvMmMJp9ygKHuuLSvBum+19zWbBjZI0KfWSgETtj76ps2ABOPdrmkDzn00UJQ/nqdc3Zc+PrKhcXO0Py5GBe/0D1NwXM1fbUH2m2tMp7ZR3Tvw8UMiDFxPZgy0roA+FtfWTVyPW2UDOFbQh9NMI0YylYGuBAE4yW2XZhZ+E0H98Zvr5M0waSMc5fv1hKHgaCkF6+/mqCr0DU69i97qwnlokaWkQnQV0o/YRGiH7a4jBQSkfBGdD9P3A33oiu4E84Xok3VKeRzFfJAmfOZen+aWccPmqZ9sxgrzWlnx4McrYpKHpENadnyepiT8mLwdKM5Ar8wrGUROcMzCuslhx/SSN/o9jgFL86KsOrx2z9U27VSVAiJQkYgOy6Y7WKbNJ4gMnyz31IkYwIe7HsA5bxFuLnklFK8fB6TM8ll09mwSJw="

before_install:
- git clone https://github.com/uyuni-project/uyuni-docs
- cd uyuni-docs/
- git checkout gh-pages
- rm -rf uyuni/3.2
- git clone https://github.com/uyuni-project/uyuni-docs-publisher
- cd uyuni-docs-publisher
- docker pull antora/antora
- docker images
- docker run -u $UID -v `pwd`:/antora --rm -t antora/antora --cache-dir=./.cache/antora uyuni-publisher.yml
- cp -r public/uyuni/3.2 ../uyuni/3.2
- cd ../
- git remote rm origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/uyuni-project/uyuni-docs.git
- git branch --set-upstream origin gh-pages
- git pull
- git add .
- git commit -am "New travis commit to Master"
- git push
- pwd
